[package]
name = "multisig-node-runtime"
version = "0.9.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
rustc-hex = "1.0"
hex-literal = "0.1.0"
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default-features = false }
parity-codec = "2.0"
parity-codec-derive = "2.0"
sr-std = { git = "https://github.com/mixbytes/substrate" }
sr-io = { git = "https://github.com/mixbytes/substrate" }
srml-support = { git = "https://github.com/mixbytes/substrate" }
substrate-primitives = { git = "https://github.com/mixbytes/substrate" }
substrate-keyring = { git = "https://github.com/mixbytes/substrate" }
srml-balances = { git = "https://github.com/mixbytes/substrate" }
srml-consensus = { git = "https://github.com/mixbytes/substrate" }
srml-executive = { git = "https://github.com/mixbytes/substrate" }
sr-primitives = { git = "https://github.com/mixbytes/substrate" }
srml-system = { git = "https://github.com/mixbytes/substrate" }
srml-timestamp = { git = "https://github.com/mixbytes/substrate" }
srml-upgrade-key = { git = "https://github.com/mixbytes/substrate" }
substrate-client = { git = "https://github.com/mixbytes/substrate", optional = true }
sr-version = { git = "https://github.com/mixbytes/substrate" }

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"substrate-primitives/std",
	"substrate-client/std",
	"sr-std/std",
	"sr-io/std",
	"srml-support/std",
	"srml-balances/std",
	"srml-consensus/std",
	"srml-executive/std",
	"sr-primitives/std",
	"srml-system/std",
	"srml-timestamp/std",
	"srml-upgrade-key/std",
	"sr-version/std",
	"serde_derive",
	"serde/std",
	"safe-mix/std",
	"substrate-client"
]
